# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-13 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200808_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='invoice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='passenger',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
