# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-04 06:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transporte', '0021_auto_20200802_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('pick_up_adress', models.CharField(max_length=100)),
                ('reciving_facility', models.CharField(max_length=100)),
                ('reason_for_transfer', models.CharField(max_length=100)),
                ('passenger_information', models.CharField(max_length=100)),
                ('pick_up_date', models.DateField(default=datetime.datetime.now, null=True)),
                ('pick_up_time', models.TimeField(null=True)),
                ('appointment_time', models.TimeField(null=True)),
                ('trip', models.CharField(choices=[('1', 'One way'), ('2', 'Two way')], max_length=1, null=True)),
                ('name_and_contact_informtion', models.CharField(max_length=100)),
                ('proof_of_service', models.CharField(max_length=100)),
                ('does_patient_requiere_special_equipment', models.CharField(max_length=100)),
                ('physical_condition', models.CharField(max_length=100)),
                ('medical_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.Medical_condition')),
            ],
        ),
    ]
