# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-13 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('appointment_type', models.CharField(blank=True, max_length=10, null=True)),
                ('invoice', models.CharField(blank=True, max_length=10, null=True)),
                ('passenger', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
