# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-17 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20200817_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='miles',
            field=models.CharField(default=12, max_length=10),
            preserve_default=False,
        ),
    ]
