# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-06-18 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('facility', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('appointment_time', models.DateField()),
                ('destiny', models.CharField(max_length=100)),
            ],
        ),
    ]
