# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-06-22 21:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_auto_20200622_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumer',
            name='requested_date_of_transportation',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
