# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-06-22 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_custumer_requested_date_of_transportation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custumer',
            new_name='Customer',
        ),
    ]
