# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-06-25 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0004_auto_20200622_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=50)),
                ('important_considerations', models.TextField(max_length=50)),
            ],
        ),
    ]
