# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-06-25 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0005_medical_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='medical_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.Medical_condition'),
        ),
    ]
