# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-06-25 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0006_auto_20200625_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_condition',
            name='important_considerations',
            field=models.TextField(max_length=500),
        ),
    ]
