# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-07-11 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0007_auto_20200625_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seivice_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('cost_per_hour', models.CharField(max_length=100)),
                ('cost_per_mile', models.CharField(max_length=100)),
            ],
        ),
    ]
