# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-07-11 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0008_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('hours', models.CharField(max_length=100)),
                ('miles', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.Services')),
            ],
        ),
    ]
