# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-07-11 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cutomer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transporte.Customer'),
            preserve_default=False,
        ),
    ]
