# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-07-11 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0010_order_cutomer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
