# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-07-11 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0011_auto_20200711_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='seivice_name',
            new_name='service_name',
        ),
    ]
