# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-07-16 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0012_auto_20200711_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('hours', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
            ],
        ),
    ]
