# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-07-16 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0013_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transporte.Customer'),
            preserve_default=False,
        ),
    ]
