# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-07-16 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0015_auto_20200716_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
