# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-02 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0019_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='facility',
        ),
    ]
