# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-02 15:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0019_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='destiny',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='facility',
            new_name='pick_up_adress',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pick_up_facility',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='requested_date_of_transportation',
        ),
        migrations.AddField(
            model_name='customer',
            name='pick_up_date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='trip',
            field=models.CharField(choices=[('1', 'One way'), ('2', 'Two way')], max_length=1, null=True),
        ),
    ]
