# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-02 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0020_auto_20200802_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='appointment_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pick_up_time',
            field=models.TimeField(null=True),
        ),
    ]
