# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-10 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passenger', '0004_auto_20200810_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('hours', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
                ('miles', models.CharField(max_length=6)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passenger.Passenger')),
            ],
        ),
    ]
